### ISSUE TITLE
Improve tests 

### ISSUE THREAD

**Issue by mariacarmina** [oceanprotocol/ocean-subgraph#665] opened 2023-04-28 12:20 UTC
**Describe the bug**
Solve suggestions from #630 

- assert specific `eventIndex`. 
- put only necessary sleeps.

**Comment by mariacarmina** [comment] 2023-05-02 13:56
UPDATE: Event index for `TokenCreated` & `NFTCreated` events are overriden in the handlers. This was discovered while trying to assert the event indexes in the tests.

E.g.: Subgraph query for a certain token's event index was 8 and in the actual tx event was 6.

**Comment by alexcos20** [comment] 2023-05-13 12:41
create another issue pls for "UPDATE: Event index for TokenCreated & NFTCreated events are overriden in the handlers. This was discovered while trying to assert the event indexes in the tests"

**Comment by mihaisc** [comment] 2023-09-24 22:01
@alexcos20 @mariacarmina status on this? can we close?

**Comment by mariacarmina** [comment] 2023-09-25 08:58
No, we cannot close this, it's still valid.

**Comment by AnaLoznianu** [comment] 2023-09-29 13:15
Duplicate of #676

**Closed by AnaLoznianu** 2023-09-29 13:15 UTC
Labels: Type: Bug
